name: breviary
channels:
  - conda-forge
dependencies:
  - pip=20.2.4
  - python=3.9.0
  - flask=1.1.2
  - gunicorn=20.0.4
  - pip:
      - pytest==6.1.2
      - typedload==2.3
      - flask-restx==0.2.0
      - flask_bcrypt==0.7.1
      - pyjwt==1.7.1
      - mypy==0.790
      - python-dateutil==2.8.1
      - psycopg2-binary==2.8.6
      - pytest==6.1.2
      - SQLAlchemy==1.3.20
      - sqlalchemy-stubs==0.3
      - typedload==2.3
      - yoyo-migrations==7.2.0
      - python-dotenv==0.15.0
